### ISSUE TITLE
feature files videoid_resnet_avg.h5 creation

### ISSUE THREAD

**Issue by sggodboy** [ckczzj/CHAN#1]
Thanks for sharing this implementation. Please also share the code files for generating feature files (videoid_resnet_avg.h5) and (videoid_c3d.h5).

**Comment by ckczzj** [comment]
> Thanks for sharing this implementation. Please also share the code files for generating feature files (videoid_resnet_avg.h5) and (videoid_c3d.h5).

All data have been uploaded to Google Drive. Please see README.

**Comment by sggodboy** [comment]
Thanks
